/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FileList: typeof import('./src/components/FileManage/FileList.vue')['default']
    FileManage: typeof import('./src/components/FileManage/FileManage.vue')['default']
    Pause: typeof import('./src/components/FileManage/icons/Pause.vue')['default']
    Upload: typeof import('./src/components/Upload/Upload.vue')['default']
  }
}
